# Generated by Django 4.2.16 on 2024-12-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=100)),
                ('size', models.DecimalField(decimal_places=2, max_digits=100)),
                ('description', models.TextField()),
                ('age_limited', models.BooleanField(default=False)),
            ],
        ),
    ]
